export const SAINT_NAMES = {
  'nayanmar.01': 'Thirunilakanda Nayanar',
  'nayanmar.02': 'Iyarpakai Nayanar',
  'nayanmar.03': 'Ilaiyankudi Mara Nayanar',
  'nayanmar.04': 'Meypporul Nayanar',
  'nayanmar.05': 'Viranminda Nayanar',
  'nayanmar.06': 'Amarnidhi Nayanar',
  'nayanmar.07': 'Eripaththa Nayanar',
  'nayanmar.08': 'Enathi Natha Nayanar',
  'nayanmar.09': 'Kannappa Nayanar',
  'nayanmar.10': 'Kunkiliyak Kalaya Nayanar',
  'nayanmar.11': 'Manak Kanchara Nayanar',
  'nayanmar.12': 'Arivattaya Nayanar',
  'nayanmar.13': 'Anaya Nayanar',
  'nayanmar.14': 'Murthi Nayanar',
  'nayanmar.15': 'Muruga Nayanar',
  'nayanmar.16': 'Rudra Pasupathi Nayanar',
  'nayanmar.17': 'Thirunalaip Povar · Nandanar',
  'nayanmar.18': 'Thirukkurippu Thondar',
  'nayanmar.19': 'Chandesha Nayanar',
  'nayanmar.20': 'Appar · Tirunavukkarasar',
  'nayanmar.21': 'Kulachirai Nayanar',
  'nayanmar.22': 'Perumizhalai Kurumba Nayanar',
  'nayanmar.23': 'Karaikkal Ammaiyar',
  'nayanmar.24': 'Appudhi Adigal',
  'nayanmar.25': 'Thiru Nilanakka Nayanar',
  'nayanmar.26': 'Naminandi Adigal',
  'nayanmar.27': 'Sambandar',
  'nayanmar.28': 'Eyarkon Kalikkamar',
  'nayanmar.29': 'Thirumular',
  'nayanmar.30': 'Dandi Adigal',
  'nayanmar.31': 'Murkha Nayanar',
  'nayanmar.32': 'Somasi Mara Nayanar',
  'nayanmar.33': 'Sakkiya Nayanar',
  'nayanmar.34': 'Sirappuli Nayanar',
  'nayanmar.35': 'Siruthonda Nayanar',
  'nayanmar.36': 'Cheraman Perumal Nayanar',
  'nayanmar.37': 'Gana Natha Nayanar',
  'nayanmar.38': 'Kootruva Nayanar',
  'nayanmar.39': 'Pugazh Chola Nayanar',
  'nayanmar.40': 'Narasinga Munaiyaraiyar',
  'nayanmar.41': 'Adipaththa Nayanar',
  'nayanmar.42': 'Kalikkamba Nayanar',
  'nayanmar.43': 'Kaliya Nayanar',
  'nayanmar.44': 'Satti Nayanar',
  'nayanmar.45': 'Aiyadigal Kadavar Kon Nayanar',
  'nayanmar.46': 'Kanampulla Nayanar',
  'nayanmar.47': 'Kari Nayanar',
  'nayanmar.48': 'Ninra Sir Nedumara Nayanar',
  'nayanmar.49': 'Vayilar Nayanar',
  'nayanmar.50': 'Munaiyaduvar Nayanar',
  'nayanmar.51': 'Kazharsinga Nayanar',
  'nayanmar.52': 'Idangazhi Nayanar',
  'nayanmar.53': 'Seruthunai Nayanar',
  'nayanmar.54': 'Pugazhthunai Nayanar',
  'nayanmar.55': 'Kotpuli Nayanar',
  'nayanmar.56': 'Pusalar Nayanar',
  'nayanmar.57': 'Mangayarkkarasiyar',
  'nayanmar.58': 'Nesa Nayanar',
  'nayanmar.59': 'Kochengat Chola Nayanar',
  'nayanmar.60': 'Thirunilakanda Yazhpanar',
  'nayanmar.61': 'Sadaiya Nayanar',
  'nayanmar.62': 'Isaignaniyar',
  'nayanmar.63': 'Sundarar · Arurar',
};
